input = [
    {'regno':123456,'highlights':[
        {
        'score':1.2,
        'texts':[
            {'value':'str','type':'hit/text'},
            {'value':'str','type':'hit/text'}
            ]
        },{
        'score':1.2,
        'texts':[
            {'value':'str','type':'hit/text'},
            {'value':'str','type':'hit/text'}
            ]
        },{
        'score':1.2,
        'texts':[
            {'value':'str','type':'hit/text'},
            {'value':'str','type':'hit/text'}
            ]
        }],
        'score':13.20
    },
    {'regno':123456,'highlights':[
        {
        'score':1.2,
        'texts':[
            {'value':'str','type':'hit/text'},
            {'value':'str','type':'hit/text'}
            ]
        },{
        'score':1.2,
        'texts':[
            {'value':'str','type':'hit/text'},
            {'value':'str','type':'hit/text'}
            ]
        },{
        'score':1.2,
        'texts':[
            {'value':'str','type':'hit/text'},
            {'value':'str','type':'hit/text'}
            ]
        }],
        'score':13.20
    },
    {'regno':123456,'highlights':[
        {
        'score':1.2,
        'texts':[
            {'value':'str','type':'hit/text'},
            {'value':'str','type':'hit/text'}
            ]
        },{
        'score':1.2,
        'texts':[
            {'value':'str','type':'hit/text'},
            {'value':'str','type':'hit/text'}
            ]
        },{
        'score':1.2,
        'texts':[
            {'value':'str','type':'hit/text'},
            {'value':'str','type':'hit/text'}
            ]
        }],
        'score':13.20
    }
    ]

if 